apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-05-06T16:50:50Z"
  generateName: php-apache-7656945b6b-
  labels:
    pod-template-hash: 7656945b6b
    run: php-apache
  name: php-apache-7656945b6b-77bnm
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: php-apache-7656945b6b
    uid: 7725f803-bf5e-4b6f-be01-9de3d7292fe4
  resourceVersion: "1038"
  uid: feb00c29-a141-4721-9690-f6394a552f1f
spec:
  containers:
  - image: k8s.gcr.io/hpa-example
    imagePullPolicy: Always
    name: php-apache
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 200m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-45xv6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: monitoring-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-45xv6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T16:50:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T16:51:06Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T16:51:06Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T16:50:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f46c3f1b08082a359b64a2367cbdbc023ad766b311617bd20f63007ab45d67d8
    image: k8s.gcr.io/hpa-example:latest
    imageID: k8s.gcr.io/hpa-example@sha256:581697a37f0e136db86d6b30392f0db40ce99c8248a7044c770012f4e8491544
    lastState: {}
    name: php-apache
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-05-06T16:51:06Z"
  hostIP: 172.18.0.5
  phase: Running
  podIP: 10.244.3.2
  podIPs:
  - ip: 10.244.3.2
  qosClass: Burstable
  startTime: "2022-05-06T16:50:51Z"
