apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: autoscaler-test
  name: autoscaler-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-test
  strategy: {}
  template:
    metadata:
      labels:
        app: autoscaler-test
    spec:
      containers:
      - image: wxwmatt/autoscaler-test:1.0
        name: autoscaler-test
        ports:
          - containerPort: 1323
        resources:
          requests:
            memory: "16Mi"
            cpu: "250m"
          limits:
            memory: "32Mi"
            cpu: "500m"
